config:
  database: "./example/test.db"
  rejected:
    - "Unknwon"
    - "Not rejected"
    - "Some other reason"
    - "Third reason"
  search: "PLC"
  show:
    - "Unknwon"
    - "Some other reason"


