config:
  database: "test.db"
  parameter:
    gui:
      rejected:
        - "Unknwon"
        - "Not rejected"
        - "Some other reason"
        - "Third reason"
      search: "Text to hightlight in the texts"


