config:
  database: "test.db"
  query_file: "query.yaml"
  parameter:
    scopus:
      token: ""
      institutional_token: ""
      partner_id: ""
    gui:
      rejected:
        - "Unknwon"
        - "Not rejected"
        - "Some other reason"
        - "Third reason"


